### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by cgermain2** [meso-upsud/meso-upsud.github.io#4]
Peut-on intégrer un flux RSS ?

**Comment by cgermain2** [comment]
Quelle bonne pratique pour disposer de documents (ex. pdf) ? Dans un repertoire, à quel niveau ?
C'est nécessaire pour par ex. lier à la présentation de génomique

**Comment by cgermain2** [comment]
Ajouter César Richard et Anne-Catherine Letournel aux users

**Comment by cgermain2** [comment]
Quand César sera utilisateur, deux commentaires pour lui : 
- Verifier et pretty formater la page DocsDonnees/AccesSFS
- Retrouver le site http://www.linkeddata.u-psud.fr et intégrer son contenu dans la page données

**Comment by jouvin** [comment]
Une bonne pratique, c'est 1 issue = 1 problème ! J'ai ouvert des issues séparées pour le [stockage des documents](#8 ) et pour la [page AccessFS](#7 ). Celle est donc dédié à l'ajout d'un flux RSS.

**Comment by jouvin** [comment]
@cgermain2 Pour moi le RSS feed était déjà configuré et fonctionnel. J'ai corrigé une meta information manquante qui pouvait perturber la découverte automatique en #9. Si tu récupères la source branch, tu peux tester et me dire si c'est ok pour toi. Sinon on corrigera ultérieurement...
